### ISSUE TITLE
Add section in information mentioning current 'big' issues

### ISSUE THREAD

**Issue by nvs** [nvs/gem#109]
The part of this project that will get the most eyes is the information presented inside the map itself. As such, it is important to mention the big talking points that may be tackled in future versions. Currently, for these would be:
- [x] The 'glitch' #16 
- [x] Balance of the map #37 
- [x] The possibility of changing the difficulty #103 
- [x] Adjusting the purpose of the Damage Test #90 
- [x] Increasing the replay value #43 
- [x] The necessity of the gamblers #25
