### ISSUE TITLE
Balance in 1.6

### ISSUE THREAD

**Issue by nvs** [nvs/gem#420]
# Balance in 1.6
This is a bit of a catch-all issue. Basically, a focal point to gather thoughts on where to take balancing in 1.6.

## Testing
- Nothing to test!

## Implemented
- [x] Check the stun duration of Dark Emeralds and Enchanted Emeralds.
- [x] Check Dark Emerald and Enchanted Emerald damage. May need a buff. Reduce cost.
- [x] Add bounce attack to Dark/Enchanted Emerald by default.
- [x] Double Ancient disarm and stun durations. This will make them a bit less efficient in their application of stuns.
- [x] Buff Malachite. Unlock target cap, increase range to be same as Mighty, and damage buff as well.
- [x] Have armor reduction from Ancients apply at a reduced value to air.
- [x] Change Ancient armor from `4/4` to `6/3`.
- [x] Maybe adjust Level 50. Right now, the minions are 55k each, and the boss is 500k. The minions being a bit stronger would increase the difficulty a bit. ~~The boss could even go to 650k.~~
- [x] Make Levels 40+ harder. Or, swap armor for more hit points.
- [x] Decrease range on Fire Star burn?
- [x] Buff Blood Stone's lightning ever so slightly.
- [x] Nerf Viper Slate's damage aura.
- [x] Deal with Stone of Bryvx.
- [x] Improve Uranium's upgrade.
- [x] Probably nerf Star Ruby DPS some too.
- [x] Town down Blood Star. Now that it improves with kills, it is pretty nuts. Even `50` DPS is pretty nuts.
- [x] Tone down Fire Star. `100` DPS is pretty nuts, especially in maze and situations that can utilize the overlap. Definitely decrease the value some. Or, perhaps the AoE range?
- [x] Decrease Ancient DPS. It stuns more frequently than every `5.0` seconds now. The DPS is too high.
- [x] Rework Dark Emeralds so their multiple bonus adds a chain to the attack. #431
- [x] Nerf (i.e. remove) Elder Slate's armor reduction gain due to kill bonuses.
- [x] Make Blood Stone have Blood Lightning instead of AoE. #430 
- [x] Remove gold bonus awarded for being first to reach certain rounds.
- [x] Rework Ancient Slates #253.
- [x] Fix Immolation damage #55. This will definitely change balance, as sources have never stacked before.
- [x] Rework Fire Star. #423 
- [x] Shift spawn location closer to first checkpoint. There is an issue about this (I think). In fact, not all spawn locations were 'correct'. Some were closer to the checkpoints than others. Some were not even aligned with the checkpoints. But we're moving them, so no point mentioning the 'fix'.
- [x] Rework swap. #113 
- [x] Allow Emerald's poison to kill. #432
- [x] Nerf Wraith Slate's AoE explosion damage. #433
- [x] Merge the Damage Test into Level 50, effectively making the Boss spawn with his minions. I hear the distant wails of players unable to finish the game now...

## Not Implementing
- [x] Elder damage when leveled may need to be reduced. **Not in 1.6.** It is possible down the line this may need to be tweaked. But, it is just one among a number of new issues to consider.
- [x] Buff more than just the 40s. Otherwise the jump from 39 to 40 is too steep. **Not in 1.6.** The concern here was in a version where air before 40 was not buffed. Since playing versions where all rounds are buffed, the jump does not seem too out of place. Air just hurts and is a real threat.
- [x] Deal with Great Opal. **Not in 1.6.** Basically, AoE damage got a buff. Don't adjust too many moving parts.
- [x] Perhaps increase Blood Lighting chance to fire. This may be necessary to compensate for the switch from 'On Attack' to 'On Damage', and how the former interacted with taunts from Hold and Ancient slates. Then again, Blood Stone should be doing more single target attack damage.
- [x] Add mana regeneration aura to Aquamarines. Numerous towers will need to be readjusted to fully utilize this change (e.g. Blood Stones, Elder, etc.). **Not in 1.6.**
- [X] Adjust a few rounds to be 'Mass' rounds now. **Not in 1.6.**
- [x] Setting the 'Reaction Delay' gameplay constant to `0`. A requirement for the delay to be used by the engine is the presence of `Amov`. No player owned damage dealing structures have `Amov`. Thus, it has never factored into Gem balanced at all. I do not foresee any towers ever having `Amov`. There is no reason to change this.
- [x] Adjust movement speed. Boost speed on many units, while increasing the effectiveness of slows. The extra speed should decrease the average game time, which is good. It will also make shorter mazes (like many early mazes) less effective. It will increase the value of having slows. And it will reduce the time discrepancy between early and middle mazes. **Not in 1.6.**
- [x] Increase the range of melee slates slightly. Currently, they are `128`. It does not feel like enough in some situations. A slightly larger range would increase the usability of slates. **Not in 1.6**
- [x] Reducing armor for all units. This will put a bit less emphasis on armor reduction as the de facto strategy (although, it will still be the main strategy by a country mile). On the flip side, it would reduce the value of spell damage somewhat.  **Not in 1.6.** Single target is still very strong.
- [x] Adjusting armor reduction values in general. Paraiba, Gold, etc. **Not in 1.6.**
