### ISSUE TITLE
Gem TD+ Reforged Issues

### ISSUE THREAD

**Issue by nvs** [nvs/gem#513]
## Bugs
- [x] ~~#514~~ - Game clock does not appear. Code changed and Reforged patched.
- [x] ~~#517~~ - The ID appears gray immediately upon cheat code detection. Configuration issue, essentially.
- [x] Loading screen text is cut off by the loading bar. Only an issue with windowed mode. Still, can shorten things though. Then again, text is justified right in 1.32.0. Not going to address this in 1.6. I would assume justified right is a mistake.
- [x] #521 - The scaling on towers is inconsistent between SD and HD. I would classify this as a Blizzard bug. That being said, the art direction in HD does not yield a very appealing conversion from SD in all cases (e.g. Perfects and Greats). It may be necessary to curate graphics for SD and HD separately. Look into using a separate `war3map.wts`. Also, verify that scaling is still off in HD as of 1.32.0.14481. *Deal with this later.*
- [x] ~Crashes. Specifically on levels 20+. Again, probably Reforged is the cause.~ *No longer present outside of beta.*
- [x] ~The ID associated with a user's BattleTag does not seem to be considered when calculating the board width.~ *This has been addressed as of 1.32.0.14481.*
- [x] #519. Perfect gems are too translucent. Going to do nothing for now. I'm hoping that this is related to changes Blizzard has made; there are other cases of things being translucent (e.g. unit portraits).
- [x] Desyncs and odd behavior related to FPS slider values less than `200` in conjunction with timed trigger events. Can switch over to using a timer directly, and this should avoid the issue.

## Research
- [x] It may not be necessary to append a line break to tooltips. This was previously done as the alignment would be too close to the bottom edge. Need to look into this. *There is enough spare room at the bottom of tooltips in 1.32.0.14481 that appending an extra line is unnecessary.*
- [x] #522 - Look into adjusting the various places of game information. The author is now listed in various places (e.g. the lobby), so other references are now redundant. *Deal with this later.*

## Tasks
- [x] Hotkeys on abilities are displayed after their name in parentheses (e.g. `Stop (S)`). This removes the need to manually edit the name to include a colored hotkey. All abilities in Gem should be updated with this information in mind.
